// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCBA.DCL.Data;

#nullable disable

namespace NCBA.DCL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221044216_CreateMFALogsAndSSOProviders")]
    partial class CreateMFALogsAndSSOProviders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NCBA.DCL.Models.Approver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeferralId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DeferralId");

                    b.HasIndex("UserId");

                    b.ToTable("Approvers");
                });

            modelBuilder.Entity("NCBA.DCL.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Resource")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceId")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedToCoCheckerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedToRMId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CheckerComment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DclNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DraftDataJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DraftExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DraftLastSaved")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FinalComment")
                        .HasColumnType("longtext");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("longtext");

                    b.Property<string>("IbpsNo")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoanType")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SubmittedToCoChecker")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToCoCheckerId");

                    b.HasIndex("AssignedToRMId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ChecklistLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("UserId");

                    b.ToTable("ChecklistLogs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.CoCreatorFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("CoCreatorFiles");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Deferral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BusinessName")
                        .HasColumnType("longtext");

                    b.Property<string>("ClosedReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentApproverIndex")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("DaysSought")
                        .HasColumnType("int");

                    b.Property<string>("DclNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("DeferralDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("DeferralNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LoanType")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NextDocumentDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<string>("ReworkComments")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SlaExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeferralNumber")
                        .IsUnique();

                    b.ToTable("Deferrals");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DeferralDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DeferralId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeferralId");

                    b.HasIndex("UploadedById");

                    b.ToTable("DeferralDocuments");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CheckerComment")
                        .HasColumnType("longtext");

                    b.Property<string>("CheckerStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorComment")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatorStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("DeferralNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("DeferralReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("RmComment")
                        .HasColumnType("longtext");

                    b.Property<string>("RmStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DocumentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.ToTable("DocumentCategories");
                });

            modelBuilder.Entity("NCBA.DCL.Models.EmailMFACode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailMFACodes");
                });

            modelBuilder.Entity("NCBA.DCL.Models.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Extension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AllApproversApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CheckerApprovalComment")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CheckerApprovalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckerApprovalStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CheckerApprovedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorApprovalComment")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatorApprovalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorApprovalStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CreatorApprovedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentApproverIndex")
                        .HasColumnType("int");

                    b.Property<int>("CurrentDaysSought")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("DclNumber")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DeferralId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeferralNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ExtensionReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("NextDocumentDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("RequestedByName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RequestedDaysSought")
                        .HasColumnType("int");

                    b.Property<string>("ReworkComments")
                        .HasColumnType("longtext");

                    b.Property<string>("ReworkRequestedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReworkRequestedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ReworkRequestedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SlaExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CheckerApprovedById");

                    b.HasIndex("CreatorApprovedById");

                    b.HasIndex("DeferralId");

                    b.HasIndex("RequestedById");

                    b.ToTable("Extensions");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ExtensionApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApprovalComment")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ExtensionId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtensionApprovers");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ExtensionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExtensionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ExtensionId");

                    b.ToTable("ExtensionComments");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ExtensionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ExtensionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.ToTable("ExtensionFiles");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ExtensionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExtensionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtensionHistories");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DeferralId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Headroom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sanctioned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeferralId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("NCBA.DCL.Models.LogoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LogoutSessions");
                });

            modelBuilder.Entity("NCBA.DCL.Models.MFALog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceFingerprint")
                        .HasColumnType("longtext");

                    b.Property<string>("FailureReason")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MFAMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("MFALogs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.MFASetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BackupCodes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EnabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBackupCodesEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTotpEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MFASetups");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<bool>("Read")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NCBA.DCL.Models.SSOConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProviderEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderProfileData")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SSOProviderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SSOProviderId", "ProviderUserId")
                        .IsUnique();

                    b.HasIndex("UserId", "SSOProviderId")
                        .IsUnique();

                    b.ToTable("SSOConnections");
                });

            modelBuilder.Entity("NCBA.DCL.Models.SSOLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SSOProviderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SSOProviderId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("SSOLogs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.SSOProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Authority")
                        .HasColumnType("longtext");

                    b.Property<string>("AuthorizationEndpoint")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RedirectUri")
                        .HasColumnType("longtext");

                    b.Property<string>("Scopes")
                        .HasColumnType("longtext");

                    b.Property<string>("TokenEndpoint")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserInfoEndpoint")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName")
                        .IsUnique();

                    b.ToTable("SSOProviders");
                });

            modelBuilder.Entity("NCBA.DCL.Models.SupportingDoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("longtext");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("UploadedByRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("UploadedById");

                    b.ToTable("SupportingDocs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.TrustedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceType")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceFingerprint");

                    b.ToTable("TrustedDevices");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Upload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentName")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("longblob");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("longtext");

                    b.Property<string>("FileUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UploadedByRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("DocumentId");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("NCBA.DCL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMFAEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMFARequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<string>("RmId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SocketIds")
                        .HasColumnType("longtext");

                    b.Property<bool>("TasksReassigned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RmId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NCBA.DCL.Models.UserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PerformedByEmail")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("TargetEmail")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.HasIndex("TargetUserId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Approver", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Deferral", "Deferral")
                        .WithMany("Approvers")
                        .HasForeignKey("DeferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Deferral");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.AuditLog", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById");

                    b.HasOne("NCBA.DCL.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId");

                    b.Navigation("PerformedBy");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Checklist", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "AssignedToCoChecker")
                        .WithMany("AssignedAsCoChecker")
                        .HasForeignKey("AssignedToCoCheckerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "AssignedToRM")
                        .WithMany("AssignedAsRM")
                        .HasForeignKey("AssignedToRMId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "CreatedBy")
                        .WithMany("CreatedChecklists")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToCoChecker");

                    b.Navigation("AssignedToRM");

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ChecklistLog", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Checklist", "Checklist")
                        .WithMany("Logs")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Checklist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.CoCreatorFile", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Document", "Document")
                        .WithMany("CoCreatorFiles")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Deferral", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "CreatedBy")
                        .WithMany("CreatedDeferrals")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DeferralDocument", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Deferral", "Deferral")
                        .WithMany("Documents")
                        .HasForeignKey("DeferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deferral");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Document", b =>
                {
                    b.HasOne("NCBA.DCL.Models.DocumentCategory", "DocumentCategory")
                        .WithMany("DocList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentCategory");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DocumentCategory", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Checklist", "Checklist")
                        .WithMany("Documents")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("NCBA.DCL.Models.EmailMFACode", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.EmailVerification", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Extension", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "CheckerApprovedBy")
                        .WithMany()
                        .HasForeignKey("CheckerApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "CreatorApprovedBy")
                        .WithMany()
                        .HasForeignKey("CreatorApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.Deferral", "Deferral")
                        .WithMany()
                        .HasForeignKey("DeferralId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckerApprovedBy");

                    b.Navigation("CreatorApprovedBy");

                    b.Navigation("Deferral");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ExtensionApprover", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Extension", "Extension")
                        .WithMany("Approvers")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Extension");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ExtensionComment", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.Extension", "Extension")
                        .WithMany("Comments")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Extension");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ExtensionFile", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Extension", "Extension")
                        .WithMany("AdditionalFiles")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extension");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ExtensionHistory", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Extension", "Extension")
                        .WithMany("History")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Extension");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Facility", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Deferral", "Deferral")
                        .WithMany("Facilities")
                        .HasForeignKey("DeferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deferral");
                });

            modelBuilder.Entity("NCBA.DCL.Models.LogoutSession", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.MFALog", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany("MFALogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.MFASetup", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithOne("MFASetup")
                        .HasForeignKey("NCBA.DCL.Models.MFASetup", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Notification", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.SSOConnection", b =>
                {
                    b.HasOne("NCBA.DCL.Models.SSOProvider", "Provider")
                        .WithMany("UserConnections")
                        .HasForeignKey("SSOProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany("SSOConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.SSOLog", b =>
                {
                    b.HasOne("NCBA.DCL.Models.SSOProvider", "Provider")
                        .WithMany("SSOLogs")
                        .HasForeignKey("SSOProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany("SSOLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.SupportingDoc", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Checklist", "Checklist")
                        .WithMany("SupportingDocs")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById");

                    b.Navigation("Checklist");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("NCBA.DCL.Models.TrustedDevice", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany("TrustedDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.UserLog", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "PerformedBy")
                        .WithMany("PerformedByLogs")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "TargetUser")
                        .WithMany("TargetUserLogs")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedBy");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Checklist", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Logs");

                    b.Navigation("SupportingDocs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Deferral", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Documents");

                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Document", b =>
                {
                    b.Navigation("CoCreatorFiles");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DocumentCategory", b =>
                {
                    b.Navigation("DocList");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Extension", b =>
                {
                    b.Navigation("AdditionalFiles");

                    b.Navigation("Approvers");

                    b.Navigation("Comments");

                    b.Navigation("History");
                });

            modelBuilder.Entity("NCBA.DCL.Models.SSOProvider", b =>
                {
                    b.Navigation("SSOLogs");

                    b.Navigation("UserConnections");
                });

            modelBuilder.Entity("NCBA.DCL.Models.User", b =>
                {
                    b.Navigation("AssignedAsCoChecker");

                    b.Navigation("AssignedAsRM");

                    b.Navigation("CreatedChecklists");

                    b.Navigation("CreatedDeferrals");

                    b.Navigation("MFALogs");

                    b.Navigation("MFASetup");

                    b.Navigation("Notifications");

                    b.Navigation("PerformedByLogs");

                    b.Navigation("SSOConnections");

                    b.Navigation("SSOLogs");

                    b.Navigation("TargetUserLogs");

                    b.Navigation("TrustedDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
